In [1]:
!pip install autogluon pandas scikit-learn

Collecting autogluon
  Downloading autogluon-1.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting autogluon.core==1.5.0 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_core-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.features==1.5.0 (from autogluon)
  Downloading autogluon_features-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.tabular==1.5.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading autogluon_tabular-1.5.0-py3-none-any.whl.metadata (16 kB)
Collecting autogluon.multimodal==1.5.0 (from autogluon)
  Downloading autogluon_multimodal-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.timeseries==1.5.0 (from autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading autogluon_timeseries-1.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.0.2)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.16.3)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.6.1)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.32.4)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.10.0)
Collecting boto3<2,>=1.10 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading boto3-1.42.68-py3-none-any.whl.metadata (6.7 kB)
Collecting autogluon.common==1.5.0 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_common-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting ray<2.53,>=2.43.0 (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0->autogluon)
  Downloading ray-2.52.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (21 kB)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (18.1.0)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (0.2.7)
Collecting stevedore<5.5 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading stevedore-5.4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: Pillow<12,>=10.0.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (11.3.0)
Collecting torch<2.10,>=2.6 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Collecting lightning<2.6,>=2.5.1 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning-2.5.6-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 kB 2.7 MB/s eta 0:00:00
Collecting transformers<4.58,>=4.51.0 (from transformers[sentencepiece]<4.58,>=4.51.0->autogluon.multimodal==1.5.0->autogluon)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 2.9 MB/s eta 0:00:00
Requirement already satisfied: accelerate<2.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.13.0)
Requirement already satisfied: fsspec<=2025.3 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (2025.3.0)
Collecting jsonschema<4.24,>=4.18 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting seqeval<1.3.0,>=1.2.2 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting evaluate<0.5.0,>=0.4.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting timm<1.0.7,>=0.9.5 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading timm-1.0.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.6 MB/s eta 0:00:00
Collecting torchvision<0.25.0,>=0.21.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchvision-0.24.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Requirement already satisfied: scikit-image<0.26.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.25.2)
Requirement already satisfied: text-unidecode<1.4,>=1.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.3)
Collecting torchmetrics<1.8,>=1.2.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchmetrics-1.7.4-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: omegaconf<2.4.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.3.0)
Collecting pytorch-metric-learning<2.9,>=1.3.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_metric_learning-2.8.1-py3-none-any.whl.metadata (18 kB)
Collecting nlpaug<1.2.0,>=1.1.10 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nlpaug-1.1.11-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: nltk<3.10,>=3.4.5 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.9.1)
Collecting openmim<0.4.0,>=0.3.7 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.1.6)
Requirement already satisfied: tensorboard<3,>=2.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.19.0)
Collecting pytesseract<0.4,>=0.3.9 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-ml-py3<8.0,>=7.352.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nvidia-ml-py3-7.352.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting pdf2image<1.19,>=1.17.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Collecting einx (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading einx-0.4.2-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (4.6.0)
Collecting huggingface_hub<1.0 (from huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Collecting xgboost<3.2,>=2.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading xgboost-3.1.3-py3-none-manylinux_2_28_x86_64.whl.metadata (2.0 kB)
Collecting catboost<1.3,>=1.2 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: fastai<2.9,>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (2.8.7)
Collecting loguru (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: einops<0.9,>=0.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (0.8.2)
Requirement already satisfied: spacy<3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (3.8.11)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (1.5.3)
Collecting gluonts<0.17,>=0.15.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading gluonts-0.16.2-py3-none-any.whl.metadata (9.8 kB)
Collecting statsforecast<2.0.2,>=1.7.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading statsforecast-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (29 kB)
Collecting mlforecast<0.15.0,>=0.14.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading mlforecast-0.14.0-py3-none-any.whl.metadata (12 kB)
Collecting utilsforecast<0.2.12,>=0.2.3 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading utilsforecast-0.2.11-py3-none-any.whl.metadata (7.7 kB)
Collecting coreforecast<0.0.17,>=0.0.12 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading coreforecast-0.0.16-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Collecting fugue>=0.9.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading fugue-0.9.7-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: orjson~=3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (3.11.7)
Collecting chronos-forecasting<2.4,>=2.2.2 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading chronos_forecasting-2.2.2-py3-none-any.whl.metadata (23 kB)
Collecting peft<0.18,>=0.13.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading peft-0.17.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: psutil<7.2.0,>=5.7.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (5.9.5)
Requirement already satisfied: pyyaml>=5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon) (26.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon) (0.7.0)
Collecting botocore<1.43.0,>=1.42.68 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading botocore-1.42.68-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (0.21)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (5.24.1)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (4.0.0)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (0.70.16)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (0.0.7)
Requirement already satisfied: fastcore>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (1.12.24)
Requirement already satisfied: fasttransform>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (0.0.2)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (1.1.5)
Requirement already satisfied: plum-dispatch in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (2.7.1)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (3.1.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (3.13.3)
Collecting triad>=1.0.1 (from fugue>=0.9.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading triad-1.0.2-py3-none-any.whl.metadata (6.6 kB)
Collecting adagio>=0.2.6 (from fugue>=0.9.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading adagio-0.2.6-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pydantic<3,>=1.7 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (2.12.3)
Requirement already satisfied: toolz~=0.10 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (0.12.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (3.25.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (1.3.2)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon) (1.0.0)
Requirement already satisfied: py4j in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon) (0.10.9.9)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.0.3->autogluon.multimodal==1.5.0->autogluon) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.30.0)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting pytorch-lightning (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_lightning-2.6.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.3.2)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (0.60.0)
Collecting optuna (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Collecting window-ops (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading window_ops-0.0.15-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: gdown>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from nlpaug<1.2.0,>=1.1.10->autogluon.multimodal==1.5.0->autogluon) (5.2.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk<3.10,>=3.4.5->autogluon.multimodal==1.5.0->autogluon) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk<3.10,>=3.4.5->autogluon.multimodal==1.5.0->autogluon) (2025.11.3)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from omegaconf<2.4.0,>=2.1.1->autogluon.multimodal==1.5.0->autogluon) (4.9.3)
Collecting colorama (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.5.0->autogluon)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting model-index (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.5.0->autogluon)
  Downloading model_index-0.1.11-py3-none-any.whl.metadata (3.9 kB)

In [2]:
import pandas as pd
import numpy as np

from autogluon.tabular import TabularPredictor
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('/content/df_all_clean (1).csv')

print(df.shape)
df.head()

(19350, 25)

,discode,Sex,agey,agem,aged,nation,occupat,addercode,metropol,treatmentloc,...,datefound,datedeath,germ,complications,district,province,death,days_to_death,days_to_define,days_to_report
0,66.0,หญิง,17,5,19,ไทย,ไม่ทราบอาชีพ,26020302,อบต,ร.พ.ชุมชน,...,2018-01-01,NaN,NaN,NaN,ปากพลี,นครนายก,0,NaN,0.0,0.0
1,66.0,ชาย,52,8,1,ไทย,รับจ้าง-กรรมกร,14081305,ในเขตเทศบาล,ร.พ.ชุมชน,...,2018-01-01,NaN,NaN,NaN,ผักไห่,พระนครศรีอยุธยา,0,NaN,0.0,0.0
2,66.0,ชาย,55,0,0,ไทย,รับจ้าง-กรรมกร,14110303,ในเขตเทศบาล,คลินิก-ร.พ.เอกชน,...,2018-01-01,NaN,9.0,0.0,วังน้อย,พระนครศรีอยุธยา,0,NaN,0.0,0.0
3,66.0,ชาย,39,0,0,ไทย,รับจ้าง-กรรมกร,14100605,อบต,ร.พ.ชุมชน,...,2018-01-01,NaN,0.0,0.0,ลาดบัวหลวง,พระนครศรีอยุธยา,0,NaN,0.0,0.0
4,66.0,ชาย,51,3,24,ไทย,รับจ้าง-กรรมกร,14051102,ในเขตเทศบาล,ร.พ.ชุมชน,...,2018-01-01,NaN,NaN,NaN,บางบาล,พระนครศรีอยุธยา,0,NaN,0.0,0.0

In [29]:
# change columns to datetime

df["datesick"] = pd.to_datetime(df["datesick"], errors="coerce")

In [31]:
# สร้าง Month Feature

df["month"] = df["datesick"].dt.to_period("M")

In [32]:
# Aggregate Cases

cases = (
    df.groupby(["province","district","month"])
    .size()
    .reset_index(name="cases")
)

In [7]:
# แปลง Month เป็น Datetime

cases["month"] = cases["month"].dt.to_timestamp()

In [8]:
# เรียงข้อมูลตามเวลา

cases = cases.sort_values(
    ["province","district","month"]
)

In [9]:
# Lag Feature (1 เดือนก่อน)

cases["cases_lag1"] = (
    cases.groupby(["province","district"])["cases"]
    .shift(1)
)

In [10]:
# Lag Feature (2 เดือนก่อน)

cases["cases_lag2"] = (
    cases.groupby(["province","district"])["cases"]
    .shift(2)
)

In [11]:
# Lag Feature (3 เดือนก่อน)

cases["cases_lag3"] = (
    cases.groupby(["province","district"])["cases"]
    .shift(3)
)

In [12]:
# Trend Feature

cases["trend"] = cases["cases_lag1"] - cases["cases_lag2"]

In [13]:
# Acceleration Feature

cases["acceleration"] = (
    cases["cases_lag1"]
    - 2*cases["cases_lag2"]
    + cases["cases_lag3"]
)

In [14]:
# Moving Average (3 เดือน)

cases["ma3"] = (
    cases.groupby(["province","district"])["cases"]
    .rolling(3)
    .mean()
    .reset_index(level=[0,1], drop=True)
)

In [15]:
# Moving Average (6 เดือน)

cases["ma6"] = (
    cases.groupby(["province","district"])["cases"]
    .rolling(6)
    .mean()
    .reset_index(level=[0,1], drop=True)
)

In [16]:
# Growth Rate

cases["growth_rate"] = (
    cases["cases_lag1"] - cases["cases_lag2"]
) / (cases["cases_lag2"] + 1)

In [17]:
# Seasonality

cases["month_num"] = cases["month"].dt.month

In [18]:
# กำหนด Hotspot

threshold = 30

cases["hotspot"] = (
    cases["cases"] > threshold
).astype(int)

In [19]:
# ลบ Missing Data

cases = cases.dropna()

In [20]:
# เลือก Feature

features = [
"province",
"district",
"cases_lag1",
"cases_lag2",
"cases_lag3",
"trend",
"acceleration",
"ma3",
"ma6",
"growth_rate",
"month_num",
"hotspot"
]

In [21]:
# เตรียม Dataset

dataset = cases[features]

In [22]:
# Split Dataset

train_data, test_data = train_test_split(
    dataset,
    test_size=0.2,
    random_state=42
)

In [23]:
# Train Model

predictor = TabularPredictor(
    label="hotspot",
    problem_type="binary",
    eval_metric="roc_auc"
).fit(
    train_data,
    presets="high_quality"
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260315_075816"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Mon Feb  2 12:27:57 UTC 2026
CPU Count:          2
Pytorch Version:    2.9.1+cu128
CUDA Version:       CUDA is not available
Memory Avail:       11.15 GB / 12.67 GB (88.0%)
Disk Space Avail:   74.75 GB / 107.72 GB (69.4%)
===================================================
Presets specified: ['high_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2026-03-15 07:58:44,829	INFO worker.py:2014 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
		Context path: "/content/AutogluonModels/ag-20260315_075816/ds_sub_fit/sub_fit_ho"
(_dystack pid=2796) Running DyStack sub-fit ...
(_dystack pid=2796) Beginning AutoGluon training ... Time limit = 879s
(_dystack pid=2796) AutoGluon will save models to "/content/AutogluonModels/ag-20260315_075816/ds_sub_fit/sub_fit_ho"
(_dystack pid=2796) Train Data Rows:    1347
(_dystack pid=2796) Train Data Columns: 11
(_dystack pid=2796) Label Column:       hotspot
(_dystack pid=2796) Problem Type:       binary
(_dystack pid=2796) Preprocessing data ...
(_dystack pid=2796) Selected class <--> label mapping:  class 1 = 1, class 0 = 0
(_dystack pid=2796) Using Feature Generators to preprocess the data ...
(_dystack pid=2796) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=2796) 	Available Memory:                    10210.27 MB
(_dystack pid=2796) 	Train Data (Original)  Memory Usage: 0.30 MB (0.0% of available memory)
(_dystack pid=2796) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=2796) 	Stage 1 Generators:
(_dystack pid=2796) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=2796) 	Stage 2 Generators:
(_dystack pid=2796) 		Fitting FillNaFeatureGenerator...
(_dystack pid=2796) 	Stage 3 Generators:
(_dystack pid=2796) 		Fitting IdentityFeatureGenerator...
(_dystack pid=2796) 		Fitting CategoryFeatureGenerator...
(_dystack pid=2796) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=2796) 	Stage 4 Generators:
(_dystack pid=2796) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=2796) 	Stage 5 Generators:
(_dystack pid=2796) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=2796) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=2796) 		('float', [])  : 8 | ['cases_lag1', 'cases_lag2', 'cases_lag3', 'trend', 'acceleration', ...]
(_dystack pid=2796) 		('int', [])    : 1 | ['month_num']
(_dystack pid=2796) 		('object', []) : 2 | ['province', 'district']
(_dystack pid=2796) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=2796) 		('category', []) : 2 | ['province', 'district']
(_dystack pid=2796) 		('float', [])    : 8 | ['cases_lag1', 'cases_lag2', 'cases_lag3', 'trend', 'acceleration', ...]
(_dystack pid=2796) 		('int', [])      : 1 | ['month_num']
(_dystack pid=2796) 	0.2s = Fit runtime
(_dystack pid=2796) 	11 features in original data used to generate 11 features in processed data.
(_dystack pid=2796) 	Train Data (Processed) Memory Usage: 0.09 MB (0.0% of available memory)
(_dystack pid=2796) Data preprocessing and feature engineering runtime = 0.17s ...
(_dystack pid=2796) AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
(_dystack pid=2796) 	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
(_dystack pid=2796) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=2796) Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
(_dystack pid=2796) User-specified model hyperparameters to be fit:
(_dystack pid=2796) {
(_dystack pid=2796) 	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
(_dystack pid=2796) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=2796) 	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
(_dystack pid=2796) 	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
(_dystack pid=2796) 	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
(_dystack pid=2796) 	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=2796) 	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=2796) }
(_dystack pid=2796) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=2796) Fitting 108 L1 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 585.60s of the 878.60s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.17%)

(_ray_fit pid=3021) [1000]	valid_set's binary_logloss: 0.0120697
(_ray_fit pid=3021) [2000]	valid_set's binary_logloss: 0.0090854

(_dystack pid=2796) 	0.9905	 = Validation score   (roc_auc)
(_dystack pid=2796) 	38.14s	 = Training   runtime
(_dystack pid=2796) 	0.18s	 = Validation runtime
(_dystack pid=2796) Fitting model: LightGBM_BAG_L1 ... Training model for up to 525.62s of the 818.62s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.18%)

(_ray_fit pid=3682) [1000]	valid_set's binary_logloss: 0.00694807
(_ray_fit pid=3682) [2000]	valid_set's binary_logloss: 0.00619771
(_ray_fit pid=3682) [3000]	valid_set's binary_logloss: 0.00630908

(_dystack pid=2796) 	0.9895	 = Validation score   (roc_auc)
(_dystack pid=2796) 	34.79s	 = Training   runtime
(_dystack pid=2796) 	0.12s	 = Validation runtime
(_dystack pid=2796) Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 482.38s of the 775.38s of remaining time.
(_dystack pid=2796) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	0.9799	 = Validation score   (roc_auc)
(_dystack pid=2796) 	2.35s	 = Training   runtime
(_dystack pid=2796) 	0.21s	 = Validation runtime
(_dystack pid=2796) Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 479.79s of the 772.78s of remaining time.
(_dystack pid=2796) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	0.9798	 = Validation score   (roc_auc)
(_dystack pid=2796) 	1.14s	 = Training   runtime
(_dystack pid=2796) 	0.17s	 = Validation runtime
(_dystack pid=2796) Fitting model: CatBoost_BAG_L1 ... Training model for up to 478.44s of the 771.44s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=3.99%)
(_dystack pid=2796) 	0.9941	 = Validation score   (roc_auc)
(_dystack pid=2796) 	63.59s	 = Training   runtime
(_dystack pid=2796) 	0.05s	 = Validation runtime
(_dystack pid=2796) Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 407.88s of the 700.88s of remaining time.
(_dystack pid=2796) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	0.9878	 = Validation score   (roc_auc)
(_dystack pid=2796) 	1.47s	 = Training   runtime
(_dystack pid=2796) 	0.24s	 = Validation runtime
(_dystack pid=2796) Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 406.14s of the 699.13s of remaining time.
(_dystack pid=2796) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	0.987	 = Validation score   (roc_auc)
(_dystack pid=2796) 	1.21s	 = Training   runtime
(_dystack pid=2796) 	0.18s	 = Validation runtime
(_dystack pid=2796) Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 404.70s of the 697.70s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.01%)
(_dystack pid=2796) 	0.9976	 = Validation score   (roc_auc)
(_dystack pid=2796) 	86.27s	 = Training   runtime
(_dystack pid=2796) 	0.27s	 = Validation runtime
(_dystack pid=2796) Fitting model: XGBoost_BAG_L1 ... Training model for up to 313.81s of the 606.80s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.12%)
(_dystack pid=2796) 	0.9906	 = Validation score   (roc_auc)
(_dystack pid=2796) 	26.74s	 = Training   runtime
(_dystack pid=2796) 	0.15s	 = Validation runtime
(_dystack pid=2796) Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 279.27s of the 572.27s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.01%)
(_ray_fit pid=6439) 	Ran out of time, stopping training early. (Stopping on epoch 185)
(_dystack pid=2796) 	0.9203	 = Validation score   (roc_auc)
(_dystack pid=2796) 	165.49s	 = Training   runtime
(_dystack pid=2796) 	0.31s	 = Validation runtime
(_dystack pid=2796) Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 107.98s of the 400.97s of remaining time.
(_ray_fit pid=6649) 	Ran out of time, stopping training early. (Stopping on epoch 257)
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.75%)
(_dystack pid=2796) 	0.9791	 = Validation score   (roc_auc)
(_dystack pid=2796) 	35.98s	 = Training   runtime
(_dystack pid=2796) 	0.09s	 = Validation runtime
(_dystack pid=2796) Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 65.86s of the 358.86s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=4.14%)
(_ray_fit pid=7486) 	Ran out of time, early stopping on iteration 1054.
(_ray_fit pid=7839) 	Ran out of time, early stopping on iteration 1141.
(_ray_fit pid=7897) 	Ran out of time, early stopping on iteration 1026.
(_dystack pid=2796) 	0.9907	 = Validation score   (roc_auc)
(_dystack pid=2796) 	55.41s	 = Training   runtime
(_dystack pid=2796) 	0.05s	 = Validation runtime
(_dystack pid=2796) Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 1.65s of the 294.65s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.01%)
(_dystack pid=2796) 	Time limit exceeded... Skipping NeuralNetTorch_r79_BAG_L1.
(_dystack pid=2796) Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 278.43s of remaining time.
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.2 GB
(_dystack pid=2796) 	Ensemble Weights: {'NeuralNetFastAI_BAG_L1': 0.5, 'XGBoost_BAG_L1': 0.25, 'CatBoost_r177_BAG_L1': 0.25}
(_dystack pid=2796) 	0.9981	 = Validation score   (roc_auc)
(_dystack pid=2796) 	0.47s	 = Training   runtime
(_dystack pid=2796) 	0.0s	 = Validation runtime
(_dystack pid=2796) Fitting 108 L2 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 277.93s of the 277.77s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.21%)
(_dystack pid=2796) 	0.9967	 = Validation score   (roc_auc)
(_dystack pid=2796) 	56.19s	 = Training   runtime
(_dystack pid=2796) 	0.22s	 = Validation runtime
(_dystack pid=2796) Fitting model: LightGBM_BAG_L2 ... Training model for up to 214.41s of the 214.25s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.21%)

(_ray_fit pid=8938) [1000]	valid_set's binary_logloss: 0.000390938

(_dystack pid=2796) 	0.991	 = Validation score   (roc_auc)
(_dystack pid=2796) 	40.22s	 = Training   runtime
(_dystack pid=2796) 	0.11s	 = Validation runtime
(_dystack pid=2796) Fitting model: RandomForestGini_BAG_L2 ... Training model for up to 167.25s of the 167.09s of remaining time.
(_dystack pid=2796) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	0.996	 = Validation score   (roc_auc)
(_dystack pid=2796) 	2.58s	 = Training   runtime
(_dystack pid=2796) 	0.23s	 = Validation runtime
(_dystack pid=2796) Fitting model: RandomForestEntr_BAG_L2 ... Training model for up to 164.39s of the 164.24s of remaining time.
(_dystack pid=2796) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	0.988	 = Validation score   (roc_auc)
(_dystack pid=2796) 	1.32s	 = Training   runtime
(_dystack pid=2796) 	0.18s	 = Validation runtime
(_dystack pid=2796) Fitting model: CatBoost_BAG_L2 ... Training model for up to 162.87s of the 162.71s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=4.09%)
(_dystack pid=2796) 	0.9959	 = Validation score   (roc_auc)
(_dystack pid=2796) 	70.76s	 = Training   runtime
(_dystack pid=2796) 	0.08s	 = Validation runtime
(_dystack pid=2796) Fitting model: ExtraTreesGini_BAG_L2 ... Training model for up to 86.19s of the 86.03s of remaining time.
(_dystack pid=2796) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	0.9884	 = Validation score   (roc_auc)
(_dystack pid=2796) 	1.75s	 = Training   runtime
(_dystack pid=2796) 	0.25s	 = Validation runtime
(_dystack pid=2796) Fitting model: ExtraTreesEntr_BAG_L2 ... Training model for up to 84.13s of the 83.97s of remaining time.
(_dystack pid=2796) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	0.9881	 = Validation score   (roc_auc)
(_dystack pid=2796) 	1.33s	 = Training   runtime
(_dystack pid=2796) 	0.18s	 = Validation runtime
(_dystack pid=2796) Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 82.59s of the 82.43s of remaining time.
(_dystack pid=2796) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.02%)
(_ray_fit pid=10435) No improvement since epoch 5: early stopping
(_ray_fit pid=10586) No improvement since epoch 7: early stopping
(_dystack pid=2796) 	0.9879	 = Validation score   (roc_auc)
(_dystack pid=2796) 	85.0s	 = Training   runtime
(_dystack pid=2796) 	0.34s	 = Validation runtime
(_dystack pid=2796) Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the -8.64s of remaining time.
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.7 GB
(_dystack pid=2796) 	Ensemble Weights: {'NeuralNetFastAI_BAG_L1': 0.4, 'LightGBMXT_BAG_L2': 0.3, 'NeuralNetFastAI_BAG_L2': 0.2, 'CatBoost_BAG_L2': 0.1}
(_dystack pid=2796) 	0.9984	 = Validation score   (roc_auc)
(_dystack pid=2796) 	0.22s	 = Training   runtime
(_dystack pid=2796) 	0.0s	 = Validation runtime
(_dystack pid=2796) AutoGluon training complete, total runtime = 887.68s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 90.2 rows/s (169 batch size)
(_dystack pid=2796) Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
(_dystack pid=2796) Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
(_dystack pid=2796) 	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
(_dystack pid=2796) 	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
(_dystack pid=2796) 	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
(_dystack pid=2796) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: LightGBMXT_BAG_L1_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.7 GB
(_dystack pid=2796) 	4.14s	 = Training   runtime
(_dystack pid=2796) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: LightGBM_BAG_L1_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.6 GB
(_dystack pid=2796) 	0.49s	 = Training   runtime
(_dystack pid=2796) Fitting model: RandomForestGini_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=2796) 	2.35s	 = Training   runtime
(_dystack pid=2796) 	0.21s	 = Validation runtime
(_dystack pid=2796) Fitting model: RandomForestEntr_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=2796) 	1.14s	 = Training   runtime
(_dystack pid=2796) 	0.17s	 = Validation runtime
(_dystack pid=2796) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: CatBoost_BAG_L1_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	2.97s	 = Training   runtime
(_dystack pid=2796) Fitting model: ExtraTreesGini_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=2796) 	1.47s	 = Training   runtime
(_dystack pid=2796) 	0.24s	 = Validation runtime
(_dystack pid=2796) Fitting model: ExtraTreesEntr_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=2796) 	1.21s	 = Training   runtime
(_dystack pid=2796) 	0.18s	 = Validation runtime
(_dystack pid=2796) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: NeuralNetFastAI_BAG_L1_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/9.5 GB
(_dystack pid=2796) 	Stopping at the best epoch learned earlier - 19.
(_dystack pid=2796) 	2.57s	 = Training   runtime
(_dystack pid=2796) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: XGBoost_BAG_L1_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	0.19s	 = Training   runtime
(_dystack pid=2796) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: NeuralNetTorch_BAG_L1_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/9.5 GB
(_dystack pid=2796) 	9.54s	 = Training   runtime
(_dystack pid=2796) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: LightGBMLarge_BAG_L1_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.5 GB
(_dystack pid=2796) 	0.76s	 = Training   runtime
(_dystack pid=2796) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: CatBoost_r177_BAG_L1_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	2.42s	 = Training   runtime
(_dystack pid=2796) Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=2796) 	Ensemble Weights: {'NeuralNetFastAI_BAG_L1': 0.5, 'XGBoost_BAG_L1': 0.25, 'CatBoost_r177_BAG_L1': 0.25}
(_dystack pid=2796) 	0.47s	 = Training   runtime
(_dystack pid=2796) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: LightGBMXT_BAG_L2_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.4 GB
(_dystack pid=2796) 	2.51s	 = Training   runtime
(_dystack pid=2796) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: LightGBM_BAG_L2_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.4 GB
(_dystack pid=2796) 	1.4s	 = Training   runtime
(_dystack pid=2796) Fitting model: RandomForestGini_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=2796) 	2.58s	 = Training   runtime
(_dystack pid=2796) 	0.23s	 = Validation runtime
(_dystack pid=2796) Fitting model: RandomForestEntr_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=2796) 	1.32s	 = Training   runtime
(_dystack pid=2796) 	0.18s	 = Validation runtime
(_dystack pid=2796) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: CatBoost_BAG_L2_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0
(_dystack pid=2796) 	2.28s	 = Training   runtime
(_dystack pid=2796) Fitting model: ExtraTreesGini_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=2796) 	1.75s	 = Training   runtime
(_dystack pid=2796) 	0.25s	 = Validation runtime
(_dystack pid=2796) Fitting model: ExtraTreesEntr_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=2796) 	1.33s	 = Training   runtime
(_dystack pid=2796) 	0.18s	 = Validation runtime
(_dystack pid=2796) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=2796) Fitting model: NeuralNetFastAI_BAG_L2_FULL ...
(_dystack pid=2796) 	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/9.5 GB
(_dystack pid=2796) 	Stopping at the best epoch learned earlier - 14.
(_dystack pid=2796) 	1.45s	 = Training   runtime
(_dystack pid=2796) Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
(_dystack pid=2796) 	Ensemble Weights: {'NeuralNetFastAI_BAG_L1': 0.4, 'LightGBMXT_BAG_L2': 0.3, 'NeuralNetFastAI_BAG_L2': 0.2, 'CatBoost_BAG_L2': 0.1}
(_dystack pid=2796) 	0.22s	 = Training   runtime
(_dystack pid=2796) Updated best model to "WeightedEnsemble_L3_FULL" (Previously "WeightedEnsemble_L3"). AutoGluon will default to using "WeightedEnsemble_L3_FULL" for predict() and predict_proba().
(_dystack pid=2796) Refit complete, total runtime = 32.94s ... Best model: "WeightedEnsemble_L3_FULL"
(_dystack pid=2796) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20260315_075816/ds_sub_fit/sub_fit_ho")
(_dystack pid=2796) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                           model  score_holdout  score_val eval_metric  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0    NeuralNetFastAI_BAG_L1_FULL       0.998236   0.997594     roc_auc        0.024528            NaN   2.570195                 0.024528                     NaN           2.570195            1       True          8
1       WeightedEnsemble_L2_FULL       0.996473   0.998072     roc_auc        0.053112            NaN   5.643455                 0.003050                     NaN           0.467583            2       True         13
2       WeightedEnsemble_L3_FULL       0.996473   0.998424     roc_auc        0.698905            NaN  34.964770                 0.004488                     NaN           0.221616            3       True         22
3         LightGBMXT_BAG_L1_FULL       0.995591   0.990515     roc_auc        0.018113            NaN   4.144639                 0.018113                     NaN           4.144639            1       True          1
4           LightGBM_BAG_L1_FULL       0.995591   0.989523     roc_auc        0.020639            NaN   0.492815                 0.020639                     NaN           0.492815            1       True          2
5         LightGBMXT_BAG_L2_FULL       0.995591   0.996721     roc_auc        0.659625            NaN  31.009901                 0.014011                     NaN           2.512787            2       True         14
6     ExtraTreesEntr_BAG_L2_FULL       0.995591   0.988123     roc_auc        0.790964            NaN  29.830126                 0.145350                0.182211           1.333011            2       True         20
7     ExtraTreesGini_BAG_L2_FULL       0.995591   0.988369     roc_auc        0.795419            NaN  30.251086                 0.149806                0.254043           1.753972            2       True         19
8     ExtraTreesGini_BAG_L1_FULL       0.994709   0.987757     roc_auc        0.117365       0.239133   1.466793                 0.117365                0.239133           1.466793            1       True          6
9      CatBoost_r177_BAG_L1_FULL       0.994709   0.990670     roc_auc        0.005358            NaN   2.417552                 0.005358                     NaN           2.417552            1       True         12
10          CatBoost_BAG_L2_FULL       0.994709   0.995905     roc_auc        0.655251            NaN  30.775446                 0.009637                     NaN           2.278332            2       True         18
11    ExtraTreesEntr_BAG_L1_FULL       0.993827   0.987025     roc_auc        0.126241       0.181586   1.214087                 0.126241                0.181586           1.214087            1       True          7
12          CatBoost_BAG_L1_FULL       0.993827   0.994118     roc_auc        0.007674            NaN   2.973449                 0.007674                     NaN           2.973449            1       True          5
13  RandomForestEntr_BAG_L1_FULL       0.993827   0.979799     roc_auc        0.123644       0.174627   1.142927                 0.123644                0.174627           1.142927            1       True          4
14  RandomForestGini_BAG_L1_FULL       0.993827   0.979947     roc_auc        0.160935       0.212567   2.349607                 0.160935                0.212567           2.349607            1       True          3
15   NeuralNetFastAI_BAG_L2_FULL       0.993827   0.987855     roc_auc        0.670770            NaN  29.952036                 0.025156                     NaN           1.454921            2       True         21
16  RandomForestGini_BAG_L2_FULL       0.992945   0.995968     roc_auc        0.779196            NaN  31.080544                 0.133582                0.225979           2.583429            2       True         16
17  RandomForestEntr_BAG_L2_FULL       0.992504   0.988038     roc_auc        0.758581            NaN  29.813104                 0.112968                0.183355           1.315990            2       True         17
18     LightGBMLarge_BAG_L1_FULL       0.992063   0.979102     roc_auc        0.013773            NaN   0.762912                 0.013773                     NaN           0.762912            1       True         11
19          LightGBM_BAG_L2_FULL       0.992063   0.990994     roc_auc        0.658344            NaN  29.892182                 0.012730                     NaN           1.395068            2       True         15
20           XGBoost_BAG_L1_FULL       0.992063   0.990607     roc_auc        0.020176            NaN   0.188125                 0.020176                     NaN           0.188125            1       True          9
21    NeuralNetTorch_BAG_L1_FULL       0.984127   0.920349     roc_auc        0.020941            NaN   9.536926                 0.020941                     NaN           9.536926            1       True         10
	0	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: True)
	949s	 = DyStack   runtime |	2651s	 = Remaining runtime
Starting main fit with num_stack_levels=0.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=0)`
Beginning AutoGluon training ... Time limit = 2651s
AutoGluon will save models to "/content/AutogluonModels/ag-20260315_075816"
Train Data Rows:    1516
Train Data Columns: 11
Label Column:       hotspot
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9682.00 MB
	Train Data (Original)  Memory Usage: 0.41 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 8 | ['cases_lag1', 'cases_lag2', 'cases_lag3', 'trend', 'acceleration', ...]
		('int', [])    : 1 | ['month_num']
		('object', []) : 2 | ['province', 'district']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 2 | ['province', 'district']
		('float', [])    : 8 | ['cases_lag1', 'cases_lag2', 'cases_lag3', 'trend', 'acceleration', ...]
		('int', [])      : 1 | ['month_num']
	0.2s = Fit runtime
	11 features in original data used to generate 11 features in processed data.
	Train Data (Processed) Memory Usage: 0.10 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.25s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],

In [33]:
# model leaderboard

predictor.leaderboard(test_data)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,NeuralNetFastAI_r145_BAG_L1_FULL,0.996097,NaN,roc_auc,0.045008,NaN,4.823346,0.045008,NaN,4.823346,1,True,63
1,CatBoost_r9_BAG_L1_FULL,0.993755,NaN,roc_auc,0.034152,NaN,6.241527,0.034152,NaN,6.241527,1,True,53
2,WeightedEnsemble_L2_FULL,0.993755,NaN,roc_auc,0.154750,NaN,8.533474,0.004782,NaN,0.252979,2,True,74
3,CatBoost_r50_BAG_L1_FULL,0.993365,NaN,roc_auc,0.008967,NaN,0.978161,0.008967,NaN,0.978161,1,True,68
4,NeuralNetFastAI_r102_BAG_L1_FULL,0.992779,NaN,roc_auc,0.075388,NaN,11.307555,0.075388,NaN,11.307555,1,True,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,NeuralNetTorch_r22_BAG_L1,NaN,0.973011,roc_auc,NaN,0.424275,235.105056,NaN,0.424275,235.105056,1,False,18
70,NeuralNetTorch_r79_BAG_L1,NaN,0.965690,roc_auc,NaN,0.368254,146.026797,NaN,0.368254,146.026797,1,False,13
71,LightGBMLarge_BAG_L1,NaN,0.957259,roc_auc,NaN,0.116834,36.362786,NaN,0.116834,36.362786,1,False,11
72,NeuralNetTorch_r86_BAG_L1,NaN,0.950359,roc_auc,NaN,0.294539,126.890838,NaN,0.294539,126.890838,1,False,30
73,NeuralNetTorch_BAG_L1,NaN,0.934585,roc_auc,NaN,0.401202,139.136194,NaN,0.401202,139.136194,1,False,10

In [25]:
# model prediction

pred = predictor.predict(test_data)

In [26]:
# Probability Prediction

prob = predictor.predict_proba(test_data)

In [27]:
# Feature Importance

predictor.feature_importance(test_data)

Computing feature importance via permutation shuffling for 11 features using 380 rows with 5 shuffle sets...
	10.62s	= Expected runtime (2.12s per shuffle set)
	3.79s	= Actual runtime (Completed 5 of 5 shuffle sets)

              importance    stddev   p_value  n  p99_high   p99_low
ma3             0.812217  0.073960  0.000008  5  0.964501  0.659933
cases_lag1      0.008314  0.002783  0.001305  5  0.014043  0.002584
cases_lag2      0.005152  0.003314  0.012714  5  0.011975 -0.001671
growth_rate     0.001717  0.002081  0.069365  5  0.006002 -0.002567
cases_lag3      0.001678  0.000449  0.000561  5  0.002603  0.000753
acceleration    0.001249  0.000509  0.002685  5  0.002297  0.000201
month_num       0.000976  0.000816  0.027827  5  0.002657 -0.000705
province        0.000351  0.000505  0.097465  5  0.001391 -0.000689
ma6             0.000078  0.000223  0.238310  5  0.000536 -0.000380
trend          -0.000078  0.000405  0.655771  5  0.000755 -0.000911
district       -0.000976  0.000717  0.980853  5  0.000501 -0.002452

In [28]:
# Save training folder from Colab to Google Drive

from google.colab import drive
import os

# 1) Mount Google Drive
drive.mount('/content/drive')

# 2) กำหนด path ของ folder ที่ต้องการ save
source_folder = "/content/AutogluonModels"   # เปลี่ยนเป็น folder ที่คุณต้องการ
zip_name = "Disease Hotspot Prediction.zip"

# 3) zip folder
!zip -r $zip_name $source_folder

# 4) copy zip file ไป Google Drive
drive_path = "/content/drive/MyDrive/"
!cp $zip_name $drive_path

# 5) แสดงผลลัพธ์
print("Saved to Google Drive:", drive_path + zip_name)

Mounted at /content/drive
	zip warning: name not matched: Hotspot
	zip warning: name not matched: Prediction.zip
  adding: content/AutogluonModels/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/learner.pkl (deflated 66%)
  adding: content/AutogluonModels/ag-20260315_075816/version.txt (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/predictor.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_075816/models/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F3/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F3/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F2/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F4/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F4/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F5/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F5/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F1/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F7/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F7/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/utils/model_template.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/utils/oof.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F6/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F6/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F8/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_BAG_L1/S1F8/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_BAG_L1_FULL/S1F1/xgb.ubj (deflated 91%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_BAG_L1_FULL/S1F1/model.pkl (deflated 58%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_BAG_L1_FULL/model.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_BAG_L1_FULL/utils/model_template.pkl (deflated 46%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBM_r188_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBM_r188_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBM_r188_BAG_L1_FULL/S1F1/model.pkl (deflated 62%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBM_r188_BAG_L1_FULL/model.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBM_r188_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBM_r188_BAG_L1_FULL/utils/model_template.pkl (deflated 45%)
  adding: content/AutogluonModels/ag-20260315_075816/models/RandomForest_r195_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/RandomForest_r195_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/RandomForest_r195_BAG_L1_FULL/S1F1/model.pkl (deflated 84%)
  adding: content/AutogluonModels/ag-20260315_075816/models/RandomForest_r195_BAG_L1_FULL/model.pkl (deflated 49%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r11_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r11_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r11_BAG_L1_FULL/S1F1/model.pkl (deflated 46%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r11_BAG_L1_FULL/S1F1/model-internals.pkl (deflated 9%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r11_BAG_L1_FULL/model.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r11_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r11_BAG_L1_FULL/utils/model_template.pkl (deflated 44%)
  adding: content/AutogluonModels/ag-20260315_075816/models/ExtraTrees_r42_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/ExtraTrees_r42_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/ExtraTrees_r42_BAG_L1/S1F1/model.pkl (deflated 81%)
  adding: content/AutogluonModels/ag-20260315_075816/models/ExtraTrees_r42_BAG_L1/model.pkl (deflated 49%)
  adding: content/AutogluonModels/ag-20260315_075816/models/ExtraTrees_r42_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/ExtraTrees_r42_BAG_L1/utils/model_template.pkl (deflated 45%)
  adding: content/AutogluonModels/ag-20260315_075816/models/ExtraTrees_r42_BAG_L1/utils/oof.pkl (deflated 79%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1_FULL/S1F1/model.pkl (deflated 17%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1_FULL/model.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1_FULL/utils/model_template.pkl (deflated 44%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r30_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r30_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r30_BAG_L1_FULL/S1F1/model.pkl (deflated 20%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r30_BAG_L1_FULL/model.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r30_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r30_BAG_L1_FULL/utils/model_template.pkl (deflated 44%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r69_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r69_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r69_BAG_L1_FULL/S1F1/model.pkl (deflated 64%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r69_BAG_L1_FULL/model.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r69_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r69_BAG_L1_FULL/utils/model_template.pkl (deflated 43%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1_FULL/S1F1/model.pkl (deflated 74%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1_FULL/model.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1_FULL/utils/model_template.pkl (deflated 43%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F3/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F3/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F2/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F4/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F4/model.pkl (deflated 49%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F5/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F5/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F1/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F7/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F7/model.pkl (deflated 49%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/utils/model_template.pkl (deflated 44%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/utils/oof.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F6/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F6/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F8/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r50_BAG_L1/S1F8/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F3/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F3/model.pkl (deflated 81%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F2/model.pkl (deflated 82%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F4/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F4/model.pkl (deflated 81%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F5/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F5/model.pkl (deflated 82%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F1/model.pkl (deflated 82%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F7/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F7/model.pkl (deflated 80%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/model.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/utils/model_template.pkl (deflated 44%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/utils/oof.pkl (deflated 46%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F6/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F6/model.pkl (deflated 80%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F8/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetTorch_r22_BAG_L1/S1F8/model.pkl (deflated 82%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r13_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r13_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r13_BAG_L1_FULL/S1F1/model.pkl (deflated 88%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r13_BAG_L1_FULL/model.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r13_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r13_BAG_L1_FULL/utils/model_template.pkl (deflated 43%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F3/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F3/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F2/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F4/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F4/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F5/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F5/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F1/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F7/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F7/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/utils/model_template.pkl (deflated 44%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/utils/oof.pkl (deflated 49%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F6/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F6/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F8/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/NeuralNetFastAI_r103_BAG_L1/S1F8/model.pkl (deflated 47%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F3/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F3/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F2/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F2/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F4/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F4/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F5/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F5/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F1/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F7/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F7/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/model.pkl (deflated 50%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/utils/model_template.pkl (deflated 43%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/utils/oof.pkl (deflated 49%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F6/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F6/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F8/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/CatBoost_r177_BAG_L1/S1F8/model.pkl (deflated 48%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBMXT_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBMXT_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBMXT_BAG_L1_FULL/S1F1/model.pkl (deflated 63%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBMXT_BAG_L1_FULL/model.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBMXT_BAG_L1_FULL/utils/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/LightGBMXT_BAG_L1_FULL/utils/model_template.pkl (deflated 46%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_r89_BAG_L1_FULL/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_r89_BAG_L1_FULL/S1F1/ (stored 0%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_r89_BAG_L1_FULL/S1F1/xgb.ubj (deflated 77%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_r89_BAG_L1_FULL/S1F1/model.pkl (deflated 57%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_r89_BAG_L1_FULL/model.pkl (deflated 51%)
  adding: content/AutogluonModels/ag-20260315_075816/models/XGBoost_r89_BAG_L1_FULL/utils/ (stored 0%)