In [3]:
import pandas as pd
import numpy as np

In [4]:
df1 = pd.read_csv('/content/Dengue_odpc4_2561.csv')
df1.head()

,discode,Sex,agey,agem,aged,nation,occupat,addercode,metropol,treatmentloc,...,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,66,หญิง,17,5,19,ไทย,ไม่ทราบอาชีพ,26020302,อบต,ร.พ.ชุมชน,...,ยังรักษาอยู่,26020300,1/1/2018,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,ปากพลี,นครนายก
1,66,หญิง,25,0,0,ไทย,รับจ้าง-กรรมกร,26040104,อบต,ร.พ.ชุมชน,...,หาย,26041000,1/1/2018,1/1/2018,1/1/2018,00-00-0000,9.0,0.0,องครักษ์,นครนายก
2,66,ชาย,23,0,0,ไทย,รับจ้าง-กรรมกร,26040104,อบต,ร.พ.ชุมชน,...,หาย,26041000,1/1/2018,1/1/2018,1/1/2018,00-00-0000,9.0,0.0,องครักษ์,นครนายก
3,66,ชาย,19,1,19,ไทย,ไม่ทราบอาชีพ,26020302,อบต,ร.พ.ชุมชน,...,ยังรักษาอยู่,26020300,1/1/2018,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,ปากพลี,นครนายก
4,66,ชาย,42,7,29,ไทย,รับจ้าง-กรรมกร,26020704,อบต,ร.พ.ชุมชน,...,หาย,26020300,1/1/2018,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,ปากพลี,นครนายก

In [5]:
# rename columns

df1 = df1.rename(columns={'occupat': 'occupation'})
df1.head()

,discode,Sex,agey,agem,aged,nation,occupation,addercode,metropol,treatmentloc,...,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,66,หญิง,17,5,19,ไทย,ไม่ทราบอาชีพ,26020302,อบต,ร.พ.ชุมชน,...,ยังรักษาอยู่,26020300,1/1/2018,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,ปากพลี,นครนายก
1,66,หญิง,25,0,0,ไทย,รับจ้าง-กรรมกร,26040104,อบต,ร.พ.ชุมชน,...,หาย,26041000,1/1/2018,1/1/2018,1/1/2018,00-00-0000,9.0,0.0,องครักษ์,นครนายก
2,66,ชาย,23,0,0,ไทย,รับจ้าง-กรรมกร,26040104,อบต,ร.พ.ชุมชน,...,หาย,26041000,1/1/2018,1/1/2018,1/1/2018,00-00-0000,9.0,0.0,องครักษ์,นครนายก
3,66,ชาย,19,1,19,ไทย,ไม่ทราบอาชีพ,26020302,อบต,ร.พ.ชุมชน,...,ยังรักษาอยู่,26020300,1/1/2018,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,ปากพลี,นครนายก
4,66,ชาย,42,7,29,ไทย,รับจ้าง-กรรมกร,26020704,อบต,ร.พ.ชุมชน,...,หาย,26020300,1/1/2018,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,ปากพลี,นครนายก

In [6]:
df2 = pd.read_csv('/content/Dengue_odpc4_2562.csv')
df2.head()

,discode,sex,agey,agem,aged,nation,occupat,addercode,metropol,treatmentloc,...,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,66,ชาย,8,7,0,ไทย,นักเรียน,14140906,อบต,คลินิก-ร.พ.เอกชน,...,ยังรักษาอยู่,14011702,1/1/2019,1/2/2019,1/5/2019,00/00/0000,9,0.0,อุทัย,พระนครศรีอยุธยา
1,66,หญิง,13,5,0,ไทย,นักเรียน,12040205,ในเขตเทศบาล,ร.พ.ชุมชน,...,ยังรักษาอยู่,12040100,1/1/2019,1/3/2019,1/3/2019,00/00/0000,9,0.0,บางบัวทอง,นนทบุรี
2,66,ชาย,61,0,0,ไทย,รับจ้าง-กรรมกร,12010401,ในเขตเทศบาล,ร.พ.ศูนย์,...,ยังรักษาอยู่,12010420,1/1/2019,1/5/2019,1/7/2019,00/00/0000,9,0.0,เมืองนนทบุรี,นนทบุรี
3,66,หญิง,28,0,0,ไทย,รับจ้าง-กรรมกร,14031005,ในเขตเทศบาล,คลินิก-ร.พ.เอกชน,...,ยังรักษาอยู่,14011302,1/1/2019,1/5/2019,1/8/2019,00/00/0000,9,0.0,นครหลวง,พระนครศรีอยุธยา
4,66,ชาย,10,2,0,ไทย,นักเรียน,16012104,อบต,ร.พ.ทั่วไป,...,ยังรักษาอยู่,16010620,1/1/2019,1/6/2019,1/11/2019,00/00/0000,9,NaN,เมืองลพบุรี,ลพบุรี

In [7]:
# rename columns

df2 = df2.rename(columns={'sex': 'Sex', 'occupat': 'occupation'})
df2.head()

,discode,Sex,agey,agem,aged,nation,occupation,addercode,metropol,treatmentloc,...,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,66,ชาย,8,7,0,ไทย,นักเรียน,14140906,อบต,คลินิก-ร.พ.เอกชน,...,ยังรักษาอยู่,14011702,1/1/2019,1/2/2019,1/5/2019,00/00/0000,9,0.0,อุทัย,พระนครศรีอยุธยา
1,66,หญิง,13,5,0,ไทย,นักเรียน,12040205,ในเขตเทศบาล,ร.พ.ชุมชน,...,ยังรักษาอยู่,12040100,1/1/2019,1/3/2019,1/3/2019,00/00/0000,9,0.0,บางบัวทอง,นนทบุรี
2,66,ชาย,61,0,0,ไทย,รับจ้าง-กรรมกร,12010401,ในเขตเทศบาล,ร.พ.ศูนย์,...,ยังรักษาอยู่,12010420,1/1/2019,1/5/2019,1/7/2019,00/00/0000,9,0.0,เมืองนนทบุรี,นนทบุรี
3,66,หญิง,28,0,0,ไทย,รับจ้าง-กรรมกร,14031005,ในเขตเทศบาล,คลินิก-ร.พ.เอกชน,...,ยังรักษาอยู่,14011302,1/1/2019,1/5/2019,1/8/2019,00/00/0000,9,0.0,นครหลวง,พระนครศรีอยุธยา
4,66,ชาย,10,2,0,ไทย,นักเรียน,16012104,อบต,ร.พ.ทั่วไป,...,ยังรักษาอยู่,16010620,1/1/2019,1/6/2019,1/11/2019,00/00/0000,9,NaN,เมืองลพบุรี,ลพบุรี

In [8]:
df3 = pd.read_csv('/content/Dengue_odpc4_2563.csv')
df3.head()

,discode,Sex,agey,agem,aged,nation,occupation,addercode,metropol,treatmentloc,...,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,66,ชาย,4,11,0,1,ไม่ทราบอาชีพ,16040602,อบต,ร.พ.ชุมชน,...,หาย,160401,1/1/2020,1/2/2020,1/8/2020,00/00/0000,9,NaN,ชัยบาดาล,ลพบุรี
1,66,ชาย,16,9,0,1,ไม่ทราบอาชีพ,16040602,อบต,ร.พ.ชุมชน,...,หาย,160401,1/1/2020,1/4/2020,1/8/2020,00/00/0000,9,NaN,ชัยบาดาล,ลพบุรี
2,66,ชาย,4,4,0,1,ไม่ทราบอาชีพ,16040602,อบต,ร.พ.ชุมชน,...,หาย,160401,1/1/2020,1/4/2020,1/8/2020,00/00/0000,9,NaN,ชัยบาดาล,ลพบุรี
3,66,หญิง,17,3,13,1,รับจ้าง-กรรมกร,14110507,อบต,ร.พ.ชุมชน,...,ยังรักษาอยู่,141104,1/1/2020,1/5/2020,1/27/2020,00/00/0000,9,NaN,วังน้อย,พระนครศรีอยุธยา
4,66,ชาย,3,3,3,1,ไม่ทราบอาชีพ,16030609,อบต,ร.พ.ชุมชน,...,ยังรักษาอยู่,160301,1/1/2020,1/5/2020,1/17/2020,00/00/0000,9,NaN,โคกสำโรง,ลพบุรี

In [9]:
df4 = pd.read_csv('/content/Dengue_odpc4_2564.csv')
df4.head()

,agey,agem,aged,nation,occupation,addercode,metropol,treatmentloc,patienttype,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,14,0,0,ไทย,นักเรียน,12010501,ในเขตเทศบาล,ร.พ.ศูนย์,ผู้ป่วยนอก,ไม่ทราบ,120104,1/1/2021,1/5/2021,1/9/2021,00/00/0000,0.0,0.0,เมืองนนทบุรี,นนทบุรี
1,6,4,10,ไทย,นักเรียน,12010306,ในเขตเทศบาล,ร.พ.ทั่วไป,ผู้ป่วยใน,ยังรักษาอยู่,120102,1/1/2021,1/5/2021,1/9/2021,00/00/0000,9.0,0.0,เมืองนนทบุรี,นนทบุรี
2,6,2,2,ไทย,นักเรียน,12040812,อบต,ร.พ.ชุมชน,ผู้ป่วยนอก,ไม่ทราบ,120301,1/2/2021,1/2/2021,1/5/2021,00/00/0000,0.0,0.0,บางบัวทอง,นนทบุรี
3,35,8,0,ไทย,ไม่ทราบอาชีพ,16012003,อบต,ร.พ.ทั่วไป,ผู้ป่วยนอก,ยังรักษาอยู่,160106,1/2/2021,1/5/2021,1/15/2021,00/00/0000,NaN,NaN,เมืองลพบุรี,ลพบุรี
4,41,1,5,ไทย,รับจ้าง-กรรมกร,12040707,ในเขตเทศบาล,คลินิก-ร.พ.เอกชน,ผู้ป่วยใน,หาย,120304,1/2/2021,1/5/2021,1/10/2021,00/00/0000,0.0,0.0,บางบัวทอง,นนทบุรี

In [10]:
# Add discode and Sex columns with NaN

df4.insert(0, 'discode', np.nan)
df4.insert(1, 'Sex', np.nan)
df4.head()

,discode,Sex,agey,agem,aged,nation,occupation,addercode,metropol,treatmentloc,...,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,NaN,NaN,14,0,0,ไทย,นักเรียน,12010501,ในเขตเทศบาล,ร.พ.ศูนย์,...,ไม่ทราบ,120104,1/1/2021,1/5/2021,1/9/2021,00/00/0000,0.0,0.0,เมืองนนทบุรี,นนทบุรี
1,NaN,NaN,6,4,10,ไทย,นักเรียน,12010306,ในเขตเทศบาล,ร.พ.ทั่วไป,...,ยังรักษาอยู่,120102,1/1/2021,1/5/2021,1/9/2021,00/00/0000,9.0,0.0,เมืองนนทบุรี,นนทบุรี
2,NaN,NaN,6,2,2,ไทย,นักเรียน,12040812,อบต,ร.พ.ชุมชน,...,ไม่ทราบ,120301,1/2/2021,1/2/2021,1/5/2021,00/00/0000,0.0,0.0,บางบัวทอง,นนทบุรี
3,NaN,NaN,35,8,0,ไทย,ไม่ทราบอาชีพ,16012003,อบต,ร.พ.ทั่วไป,...,ยังรักษาอยู่,160106,1/2/2021,1/5/2021,1/15/2021,00/00/0000,NaN,NaN,เมืองลพบุรี,ลพบุรี
4,NaN,NaN,41,1,5,ไทย,รับจ้าง-กรรมกร,12040707,ในเขตเทศบาล,คลินิก-ร.พ.เอกชน,...,หาย,120304,1/2/2021,1/5/2021,1/10/2021,00/00/0000,0.0,0.0,บางบัวทอง,นนทบุรี

In [11]:
df5 = pd.read_csv('/content/Dengue_odpc4_2565.csv')
df5.head()

,agey,agem,aged,nation,occupation,addercode,metropol,treatmentloc,patienttype,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,8,4,0,ไทย,นักเรียน,19130410,อบต,ร.พ.ศูนย์,ผู้ป่วยใน,ยังรักษาอยู่,190101,1/1/2022,1/6/2022,1/21/2022,00/00/0000,0.0,0.0,เฉลิมพระเกียรติ,สระบุรี
1,51,0,0,ไทย,รับจ้าง-กรรมกร,13020101,ในเขตเทศบาล,ร.พ.ทั่วไป,ผู้ป่วยใน,ยังรักษาอยู่,130201,1/2/2022,1/6/2022,12/26/2022,00/00/0000,0.0,0.0,คลองหลวง,ปทุมธานี
2,40,0,0,พม่า,รับจ้าง-กรรมกร,13060408,ในเขตเทศบาล,ร.พ.ทั่วไป,ผู้ป่วยนอก,ยังรักษาอยู่,130201,1/5/2022,1/5/2022,12/26/2022,00/00/0000,0.0,0.0,ลำลูกกา,ปทุมธานี
3,62,2,24,ไทย,อื่นๆ,190201,อบต,ร.พ.ชุมชน,ผู้ป่วยนอก,ยังรักษาอยู่,190201,1/6/2022,1/6/2022,1/19/2022,00/00/0000,NaN,NaN,แก่งคอย,สระบุรี
4,5,0,0,ไทย,ไม่ทราบอาชีพ,13050311,อบต,ร.พ.ทั่วไป,ผู้ป่วยนอก,ยังรักษาอยู่,130101,1/9/2022,1/13/2022,3/24/2022,00/00/0000,0.0,0.0,ลาดหลุมแก้ว,ปทุมธานี

In [12]:
# Add discode and Sex columns with NaN

df5.insert(0, 'discode', np.nan)
df5.insert(1, 'Sex', np.nan)
df5.head()

,discode,Sex,agey,agem,aged,nation,occupation,addercode,metropol,treatmentloc,...,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,NaN,NaN,8,4,0,ไทย,นักเรียน,19130410,อบต,ร.พ.ศูนย์,...,ยังรักษาอยู่,190101,1/1/2022,1/6/2022,1/21/2022,00/00/0000,0.0,0.0,เฉลิมพระเกียรติ,สระบุรี
1,NaN,NaN,51,0,0,ไทย,รับจ้าง-กรรมกร,13020101,ในเขตเทศบาล,ร.พ.ทั่วไป,...,ยังรักษาอยู่,130201,1/2/2022,1/6/2022,12/26/2022,00/00/0000,0.0,0.0,คลองหลวง,ปทุมธานี
2,NaN,NaN,40,0,0,พม่า,รับจ้าง-กรรมกร,13060408,ในเขตเทศบาล,ร.พ.ทั่วไป,...,ยังรักษาอยู่,130201,1/5/2022,1/5/2022,12/26/2022,00/00/0000,0.0,0.0,ลำลูกกา,ปทุมธานี
3,NaN,NaN,62,2,24,ไทย,อื่นๆ,190201,อบต,ร.พ.ชุมชน,...,ยังรักษาอยู่,190201,1/6/2022,1/6/2022,1/19/2022,00/00/0000,NaN,NaN,แก่งคอย,สระบุรี
4,NaN,NaN,5,0,0,ไทย,ไม่ทราบอาชีพ,13050311,อบต,ร.พ.ทั่วไป,...,ยังรักษาอยู่,130101,1/9/2022,1/13/2022,3/24/2022,00/00/0000,0.0,0.0,ลาดหลุมแก้ว,ปทุมธานี

In [13]:
df6 = pd.read_csv('/content/Dengue_odpc4_2566.csv')
df6.head()

,discode,Sex,agey,agem,aged,nation,occupation,addercode,metropol,treatmentloc,...,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,66,ชาย,13,9,0,ไทย,นักเรียน,16010606,ในเขตเทศบาล,ร.พ.ทั่วไป,...,ยังรักษาอยู่,160106,7/1/2023,9/1/2023,10/1/2023,0000-00-00,NaN,NaN,เมืองลพบุรี,ลพบุรี
1,66,หญิง,20,7,0,ไทย,รับจ้าง-กรรมกร,16010604,ในเขตเทศบาล,ร.พ.ทั่วไป,...,ยังรักษาอยู่,160106,4/1/2023,9/1/2023,10/1/2023,0000-00-00,NaN,NaN,เมืองลพบุรี,ลพบุรี
2,66,หญิง,4,6,0,ไทย,ไม่ทราบอาชีพ,16010504,ในเขตเทศบาล,ร.พ.ทั่วไป,...,ยังรักษาอยู่,160106,5/1/2023,10/1/2023,13/1/2023,0000-00-00,NaN,NaN,เมืองลพบุรี,ลพบุรี
3,66,หญิง,8,6,0,ไทย,นักเรียน,16061704,อบต.,ร.พ.ทั่วไป,...,ยังรักษาอยู่,160106,6/1/2023,10/1/2023,13/1/2023,0000-00-00,NaN,NaN,บ้านหมี่,ลพบุรี
4,66,หญิง,16,0,0,ไทย,นักเรียน,16011508,ในเขตเทศบาล,ร.พ.ทั่วไป,...,ยังรักษาอยู่,160106,5/1/2023,9/1/2023,13/1/2023,0000-00-00,NaN,NaN,เมืองลพบุรี,ลพบุรี

In [14]:
# check data schema

print(df1.columns)
print(df2.columns)
print(df3.columns)
print(df4.columns)
print(df5.columns)
print(df6.columns)

Index(['discode', 'Sex', 'agey', 'agem', 'aged', 'nation', 'occupation',
       'addercode', 'metropol', 'treatmentloc', 'patienttype', 'results',
       'treatmentloccod', 'datesick', 'datedefine', 'datefound', 'datedeath',
       'germ', 'complications', 'district', 'province'],
      dtype='object')
Index(['discode', 'Sex', 'agey', 'agem', 'aged', 'nation', 'occupation',
       'addercode', 'metropol', 'treatmentloc', 'patienttype', 'results',
       'treatmentloccod', 'datesick', 'datedefine', 'datefound', 'datedeath',
       'germ', 'complications', 'district', 'province'],
      dtype='object')
Index(['discode', 'Sex', 'agey', 'agem', 'aged', 'nation', 'occupation',
       'addercode', 'metropol', 'treatmentloc', 'patienttype', 'results',
       'treatmentloccod', 'datesick', 'datedefine', 'datefound', 'datedeath',
       'germ', 'complications', 'district', 'province'],
      dtype='object')
Index(['discode', 'Sex', 'agey', 'agem', 'aged', 'nation', 'occupation',
       'addercode', 'metropol', 'treatmentloc', 'patienttype', 'results',
       'treatmentloccod', 'datesick', 'datedefine', 'datefound', 'datedeath',
       'germ', 'complications', 'district', 'province'],
      dtype='object')
Index(['discode', 'Sex', 'agey', 'agem', 'aged', 'nation', 'occupation',
       'addercode', 'metropol', 'treatmentloc', 'patienttype', 'results',
       'treatmentloccod', 'datesick', 'datedefine', 'datefound', 'datedeath',
       'germ', 'complications', 'district', 'province'],
      dtype='object')
Index(['discode', 'Sex', 'agey', 'agem', 'aged', 'nation', 'occupation',
       'addercode', 'metropol', 'treatmentloc', 'patienttype', 'results',
       'treatmentloccod', 'datesick', 'datedefine', 'datefound', 'datedeath',
       'germ', 'complications', 'district', 'province'],
      dtype='object')

In [15]:
# Merge 6 year Dataset

import pandas as pd

df1 = pd.read_csv('/content/Dengue_odpc4_2561.csv')
df2 = pd.read_csv('/content/Dengue_odpc4_2562.csv')
df3 = pd.read_csv('/content/Dengue_odpc4_2563.csv')
df4 = pd.read_csv('/content/Dengue_odpc4_2564.csv')
df5 = pd.read_csv('/content/Dengue_odpc4_2565.csv')
df6 = pd.read_csv('/content/Dengue_odpc4_2566.csv')

df_all = pd.concat([df1, df2, df3, df4, df5, df6], ignore_index=True)

df_all['datesick'] = pd.to_datetime(df_all['datesick'], errors='coerce')

df_all = df_all.sort_values('datesick').reset_index(drop=True)

df_all

,discode,Sex,agey,agem,aged,nation,occupat,addercode,metropol,treatmentloc,...,datesick,datedefine,datefound,datedeath,germ,complications,district,province,sex,occupation
0,66.0,หญิง,17,5,19,ไทย,ไม่ทราบอาชีพ,26020302,อบต,ร.พ.ชุมชน,...,2018-01-01,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,ปากพลี,นครนายก,NaN,NaN
1,66.0,ชาย,52,8,1,ไทย,รับจ้าง-กรรมกร,14081305,ในเขตเทศบาล,ร.พ.ชุมชน,...,2018-01-01,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,ผักไห่,พระนครศรีอยุธยา,NaN,NaN
2,66.0,ชาย,55,0,0,ไทย,รับจ้าง-กรรมกร,14110303,ในเขตเทศบาล,คลินิก-ร.พ.เอกชน,...,2018-01-01,1/1/2018,1/1/2018,00-00-0000,9.0,0.0,วังน้อย,พระนครศรีอยุธยา,NaN,NaN
3,66.0,ชาย,39,0,0,ไทย,รับจ้าง-กรรมกร,14100605,อบต,ร.พ.ชุมชน,...,2018-01-01,1/1/2018,1/1/2018,00-00-0000,0.0,0.0,ลาดบัวหลวง,พระนครศรีอยุธยา,NaN,NaN
4,66.0,ชาย,51,3,24,ไทย,รับจ้าง-กรรมกร,14051102,ในเขตเทศบาล,ร.พ.ชุมชน,...,2018-01-01,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,บางบาล,พระนครศรีอยุธยา,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19345,66.0,ชาย,17,0,0,ไทย,NaN,14050807,ในเขตเทศบาล,ร.พ.ทั่วไป,...,NaT,30/7/2023,4/8/2023,0000-00-00,9.0,0.0,บางบาล,พระนครศรีอยุธยา,NaN,นักเรียน
19346,66.0,หญิง,20,0,0,ไทย,NaN,14011401,อบต.,ร.พ.ศูนย์,...,NaT,4/8/2023,7/8/2023,0000-00-00,9.0,0.0,พระนครศรีอยุธยา,พระนครศรีอยุธยา,NaN,นักเรียน
19347,66.0,ชาย,3,0,0,ไทย,NaN,14010801,อบต.,ร.พ.ศูนย์,...,NaT,28/11/2023,1/12/2023,0000-00-00,9.0,0.0,พระนครศรีอยุธยา,พระนครศรีอยุธยา,NaN,ไม่ทราบอาชีพ
19348,66.0,หญิง,29,9,21,ไทย,NaN,26011109,อบต.,ร.พ.ทั่วไป,...,NaT,28/12/2023,4/1/2024,0000-00-00,NaN,NaN,เมืองนครนายก,นครนายก,NaN,นักเรียน
19349,66.0,ชาย,47,0,0,ไทย,NaN,26011313,ในเขตเทศบาล,ร.พ.ทั่วไป,...,NaT,28/12/2023,4/1/2024,0000-00-00,9.0,0.0,เมืองนครนายก,นครนายก,NaN,ทหาร-ตำรวจ

In [16]:
# รวมไฟล์ข้อมูลทั้ง 6 ปี

df_all.to_csv('/content/dengue_2561_2566_merged.csv', index=False)

**Data Cleansing Process**

In [17]:
# check Schema

df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19350 entries, 0 to 19349
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   discode          17520 non-null  float64
 1   Sex              14192 non-null  object
 2   agey             19350 non-null  int64
 3   agem             19350 non-null  int64
 4   aged             19350 non-null  int64
 5   nation           19350 non-null  object
 6   occupat          7919 non-null   object
 7   addercode        19350 non-null  object
 8   metropol         19350 non-null  object
 9   treatmentloc     19350 non-null  object
 10  patienttype      19350 non-null  object
 11  results          19350 non-null  object
 12  treatmentloccod  19350 non-null  object
 13  datesick         15076 non-null  datetime64[ns]
 14  datedefine       19350 non-null  object
 15  datefound        19350 non-null  object
 16  datedeath        19350 non-null  object
 17  germ             12798 non-null  float64
 18  complications    8915 non-null   float64
 19  district         19339 non-null  object
 20  province         19350 non-null  object
 21  sex              3328 non-null   object
 22  occupation       11406 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(3), object(16)
memory usage: 3.4+ MB

In [35]:
# drop columns ที่ซ้ำจากการ merge

df_all = df_all.drop(['sex', 'occupation'], axis='columns')

df_all

,discode,Sex,agey,agem,aged,nation,occupat,addercode,metropol,treatmentloc,...,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,66.0,หญิง,17,5,19,ไทย,ไม่ทราบอาชีพ,26020302,อบต,ร.พ.ชุมชน,...,ยังรักษาอยู่,26020300,2018-01-01,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,ปากพลี,นครนายก
1,66.0,ชาย,52,8,1,ไทย,รับจ้าง-กรรมกร,14081305,ในเขตเทศบาล,ร.พ.ชุมชน,...,ยังรักษาอยู่,14080500,2018-01-01,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,ผักไห่,พระนครศรีอยุธยา
2,66.0,ชาย,55,0,0,ไทย,รับจ้าง-กรรมกร,14110303,ในเขตเทศบาล,คลินิก-ร.พ.เอกชน,...,ยังรักษาอยู่,14011702,2018-01-01,1/1/2018,1/1/2018,00-00-0000,9.0,0.0,วังน้อย,พระนครศรีอยุธยา
3,66.0,ชาย,39,0,0,ไทย,รับจ้าง-กรรมกร,14100605,อบต,ร.พ.ชุมชน,...,หาย,14100100,2018-01-01,1/1/2018,1/1/2018,00-00-0000,0.0,0.0,ลาดบัวหลวง,พระนครศรีอยุธยา
4,66.0,ชาย,51,3,24,ไทย,รับจ้าง-กรรมกร,14051102,ในเขตเทศบาล,ร.พ.ชุมชน,...,ยังรักษาอยู่,14050400,2018-01-01,1/1/2018,1/1/2018,00-00-0000,NaN,NaN,บางบาล,พระนครศรีอยุธยา
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19345,66.0,ชาย,17,0,0,ไทย,NaN,14050807,ในเขตเทศบาล,ร.พ.ทั่วไป,...,ยังรักษาอยู่,141407,NaT,30/7/2023,4/8/2023,0000-00-00,9.0,0.0,บางบาล,พระนครศรีอยุธยา
19346,66.0,หญิง,20,0,0,ไทย,NaN,14011401,อบต.,ร.พ.ศูนย์,...,ยังรักษาอยู่,140101,NaT,4/8/2023,7/8/2023,0000-00-00,9.0,0.0,พระนครศรีอยุธยา,พระนครศรีอยุธยา
19347,66.0,ชาย,3,0,0,ไทย,NaN,14010801,อบต.,ร.พ.ศูนย์,...,ยังรักษาอยู่,140101,NaT,28/11/2023,1/12/2023,0000-00-00,9.0,0.0,พระนครศรีอยุธยา,พระนครศรีอยุธยา
19348,66.0,หญิง,29,9,21,ไทย,NaN,26011109,อบต.,ร.พ.ทั่วไป,...,ยังรักษาอยู่,260101,NaT,28/12/2023,4/1/2024,0000-00-00,NaN,NaN,เมืองนครนายก,นครนายก
19349,66.0,ชาย,47,0,0,ไทย,NaN,26011313,ในเขตเทศบาล,ร.พ.ทั่วไป,...,ยังรักษาอยู่,260113,NaT,28/12/2023,4/1/2024,0000-00-00,9.0,0.0,เมืองนครนายก,นครนายก

In [37]:
# Check missing values

df_all.isnull().sum()

discode             1830
Sex                 5158
agey                   0
agem                   0
aged                   0
nation                 0
occupat            11431
addercode              0
metropol               0
treatmentloc           0
patienttype            0
results                0
treatmentloccod        0
datesick            4274
datedefine             0
datefound              0
datedeath              0
germ                6552
complications      10435
district              11
province               0
dtype: int64

In [38]:
# Check missing values (%)

(df_all.isnull().sum() / len(df_all)) * 100

discode             9.457364
Sex                26.656331
agey                0.000000
agem                0.000000
aged                0.000000
nation              0.000000
occupat            59.074935
addercode           0.000000
metropol            0.000000
treatmentloc        0.000000
patienttype         0.000000
results             0.000000
treatmentloccod     0.000000
datesick           22.087855
datedefine          0.000000
datefound           0.000000
datedeath           0.000000
germ               33.860465
complications      53.927649
district            0.056848
province            0.000000
dtype: float64

In [39]:
df_all.describe()

,discode,agey,agem,aged,datesick,germ,complications
count,17520.0,19350.000000,19350.000000,19350.000000,15076,12798.000000,8915.00000
mean,66.0,21.652455,3.736331,7.352765,2020-05-05 23:07:33.701247232,6.464604,0.00101
min,66.0,0.000000,0.000000,0.000000,2018-01-01 00:00:00,0.000000,0.00000
25%,66.0,10.000000,0.000000,0.000000,2018-01-01 00:00:00,0.000000,0.00000
50%,66.0,17.000000,3.000000,0.000000,2019-11-04 00:00:00,9.000000,0.00000
75%,66.0,29.000000,7.000000,15.000000,2022-09-24 00:00:00,9.000000,0.00000
max,66.0,97.000000,11.000000,30.000000,2024-06-01 00:00:00,9.000000,9.00000
std,0.0,16.209836,3.844601,9.640588,NaN,4.044794,0.09532

In [40]:
df_all['province'].unique()

array(['นครนายก', 'พระนครศรีอยุธยา', 'ลพบุรี', 'ปทุมธานี', 'สิงห์บุรี',
       'นนทบุรี', 'อ่างทอง', 'สระบุรี'], dtype=object)

In [41]:
df_all['Sex'].value_counts()

Sex
ชาย     7294
หญิง    6898
Name: count, dtype: int64

In [33]:
df_all['datesick'].dt.year.value_counts().sort_index()

datesick
2018.0    4591
2019.0    3328
2020.0    2500
2021.0     252
2022.0    1583
2023.0    2815
2024.0       7
Name: count, dtype: int64

In [32]:
report = pd.DataFrame({
    "missing": df_all.isnull().sum(),
    "dtype": df_all.dtypes,
    "unique": df_all.nunique()
})

report

                 missing           dtype  unique
discode             1830         float64       1
Sex                 5158          object       2
agey                   0           int64      96
agem                   0           int64      12
aged                   0           int64      31
nation                 0          object      14
occupat            11431          object      16
addercode              0          object    5381
metropol               0          object       3
treatmentloc           0          object       8
patienttype            0          object       2
results                0          object       4
treatmentloccod        0          object     331
datesick            4274  datetime64[ns]    1288
datedefine             0          object    1493
datefound              0          object    1274
datedeath              0          object       6
germ                6552         float64       6
complications      10435         float64       2
district              11          object      74
province               0          object       8
sex                16022          object       2
occupation          7944          object      16

ปัญหาที่พบ datesick มี missing ถึง 4274 record ตีเป็น 22.08 % ซึ่งไม่ควร drop เพราะเป็นข้อมูลที่สำคัญหาจะดูเป็น time series

In [46]:
print(df_all['datesick'].isnull().sum())
print(df_all['datesick'].isnull().mean() * 100)

4274
22.08785529715762

จะแก้ปัญหาโดยใช้ datefine ไปเติมในช่อง datesick เพราะวันวินิจฉัยจะใกล้เคียง กับวันเริ่มป่วยมากที่สุด เเละ datefine ไม่มี missing ปัญหาอาจเกิดจากผู้ป่วยไม่สามารถระบุได้ชัดเจนว่าเริ่มป่วยตั้งเเต่วันไหน

In [48]:
df_all['datedefine'].isnull().sum()

np.int64(0)

In [58]:
# เติม NaN ของ datesick ด้วยข้อมูลของ datefine

df_all['datesick'] = df_all['datesick'].fillna(df_all['datedefine'])

In [61]:
df_all['datesick'].isnull().sum()   # หากเป็น 0 เเสดงว่าเติมข้อมูลสำเร็จเเล้ว

np.int64(0)

ปัญหาที่สองคือ columns จำพวก date ยังเป็น string ซึ่งควรแปลงเป็น datetime เพื่อให้นำไปวิเคราะห์ได้

In [67]:
df_all['datedefine'] = pd.to_datetime(df_all['datedefine'], errors='coerce')
df_all['datefound'] = pd.to_datetime(df_all['datefound'], errors='coerce')
df_all['datedeath'] = pd.to_datetime(df_all['datedeath'], errors='coerce')

/tmp/ipykernel_175/303038181.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_all['datedeath'] = pd.to_datetime(df_all['datedeath'], errors='coerce')

อาจจะมีรูปเเบบการเก็บข้อมูลที่ต่างกันใน datedeath เลยขึ้น output เเบบนี้

In [70]:
df_all

,discode,Sex,agey,agem,aged,nation,occupat,addercode,metropol,treatmentloc,...,results,treatmentloccod,datesick,datedefine,datefound,datedeath,germ,complications,district,province
0,66.0,หญิง,17,5,19,ไทย,ไม่ทราบอาชีพ,26020302,อบต,ร.พ.ชุมชน,...,ยังรักษาอยู่,26020300,2018-01-01,2018-01-01,2018-01-01,NaT,NaN,NaN,ปากพลี,นครนายก
1,66.0,ชาย,52,8,1,ไทย,รับจ้าง-กรรมกร,14081305,ในเขตเทศบาล,ร.พ.ชุมชน,...,ยังรักษาอยู่,14080500,2018-01-01,2018-01-01,2018-01-01,NaT,NaN,NaN,ผักไห่,พระนครศรีอยุธยา
2,66.0,ชาย,55,0,0,ไทย,รับจ้าง-กรรมกร,14110303,ในเขตเทศบาล,คลินิก-ร.พ.เอกชน,...,ยังรักษาอยู่,14011702,2018-01-01,2018-01-01,2018-01-01,NaT,9.0,0.0,วังน้อย,พระนครศรีอยุธยา
3,66.0,ชาย,39,0,0,ไทย,รับจ้าง-กรรมกร,14100605,อบต,ร.พ.ชุมชน,...,หาย,14100100,2018-01-01,2018-01-01,2018-01-01,NaT,0.0,0.0,ลาดบัวหลวง,พระนครศรีอยุธยา
4,66.0,ชาย,51,3,24,ไทย,รับจ้าง-กรรมกร,14051102,ในเขตเทศบาล,ร.พ.ชุมชน,...,ยังรักษาอยู่,14050400,2018-01-01,2018-01-01,2018-01-01,NaT,NaN,NaN,บางบาล,พระนครศรีอยุธยา
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19345,66.0,ชาย,17,0,0,ไทย,NaN,14050807,ในเขตเทศบาล,ร.พ.ทั่วไป,...,ยังรักษาอยู่,141407,2023-07-30,NaT,2023-04-08,NaT,9.0,0.0,บางบาล,พระนครศรีอยุธยา
19346,66.0,หญิง,20,0,0,ไทย,NaN,14011401,อบต.,ร.พ.ศูนย์,...,ยังรักษาอยู่,140101,2023-04-08,2023-04-08,2023-07-08,NaT,9.0,0.0,พระนครศรีอยุธยา,พระนครศรีอยุธยา
19347,66.0,ชาย,3,0,0,ไทย,NaN,14010801,อบต.,ร.พ.ศูนย์,...,ยังรักษาอยู่,140101,2023-11-28,NaT,2023-01-12,NaT,9.0,0.0,พระนครศรีอยุธยา,พระนครศรีอยุธยา
19348,66.0,หญิง,29,9,21,ไทย,NaN,26011109,อบต.,ร.พ.ทั่วไป,...,ยังรักษาอยู่,260101,2023-12-28,NaT,2024-04-01,NaT,NaN,NaN,เมืองนครนายก,นครนายก
19349,66.0,ชาย,47,0,0,ไทย,NaN,26011313,ในเขตเทศบาล,ร.พ.ทั่วไป,...,ยังรักษาอยู่,260113,2023-12-28,NaT,2024-04-01,NaT,9.0,0.0,เมืองนครนายก,นครนายก

In [69]:
df_all['datedeath'].head(20)

0    NaT
1    NaT
2    NaT
3    NaT
4    NaT
5    NaT
6    NaT
7    NaT
8    NaT
9    NaT
10   NaT
11   NaT
12   NaT
13   NaT
14   NaT
15   NaT
16   NaT
17   NaT
18   NaT
19   NaT
Name: datedeath, dtype: datetime64[ns]

In [68]:
df_all['datedeath'].unique()[:20]

<DatetimeArray>
['NaT', '2020-07-09 00:00:00', '2023-01-09 00:00:00', '2023-09-20 00:00:00']
Length: 4, dtype: datetime64[ns]